export const DATA_API_ACTION_TYPES = {
	FETCH_DATAS_START: "data-api/FETCH_DATAS_START",
	FETCH_DATAS_SUCCESS: "data-api/FETCH_DATAS_SUCCESS",
	//
	FETCH_MOVIE_START: "data-api/FETCH_MOVIE_START",
	FETCH_MOVIE_SUCCESS: "data-api/FETCH_MOVIE_SUCCESS",
	//
	FETCH_TV_START: "data-api/FETCH_TV_START",
	FETCH_TV_SUCCESS: "data-api/FETCH_TV_SUCCESS",
	//
	FETCH_DETAIL_START: "data-api/FETCH_DETAIL_START",
	FETCH_DETAIL_SUCCESS: "data-api/FETCH_DETAIL_SUCCESS",
	//
	// FETCH_CAST_START: "data-api/FETCH_CAST_START",
	FETCH_CAST_SUCCESS: "data-api/FETCH_CAST_SUCCESS",
	//
	FETCH_SEARCH_START: "data-api/FETCH_SEARCH_START",
	FETCH_SEARCH_SUCCESS: "data-api/FETCH_SEARCH_SUCCESS",
	//
	FETCH_FAILED: "data-api/FETCH_FAILED",
};
