export const DATA_API_ACTION_TYPES = {
	FETCH_DATAS_START: "data-api/FETCH_DATAS_START",
	FETCH_DATAS_SUCCESS: "data-api/FETCH_DATAS_SUCCESS",
	FETCH_MOVIE_SUCCESS: "data-api/FETCH_MOVIE_SUCCESS",
	FETCH_TV_SUCCESS: "data-api/FETCH_TV_SUCCESS",
	FETCH_DATAS_FAILED: "data-api/FETCH_DATAS_FAILED",
};
